program: train.py

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "-config"
  - "config-base.yaml"
  - ${args}

project: test-sweep

method: random

metric:
  goal: minimize
  name: val_loss

early_terminate:
  type: hyperband
  s: 2
  eta: 3
  max_iter: 27

parameters:
  lr_init:
    distribution: log_uniform_values
    min: 1.e-6
    max: 1.e-2

  lr_exp_decay_per_epoch:
    distribution: log_uniform_values
    min: 0.9
    max: 1

  num_conv_layers:
    values: [1, 2, 3, 4, 5]