program: train.py

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "-config"
  - "config-base.yaml"
  - ${args}

project: test-sweep

method: random

metric:
  goal: minimize
  name: val_loss

early_terminate:
  type: hyperband
  s: 2
  eta: 3
  max_iter: 27

parameters:
  lr_init:
    values: [1.e-5, 1.e-4, 1.e-3]