# sweep-config.yaml: Config for `wandb` hyperparameter sweep.
# Usage: sbatch sweep.sb
#
# Note: To run the sweep in an interactive session (e.g. for debugging),
#     wandb sweep sweep-config.yaml
# This is not recommended for actual training (use sbatch instead).

program: train.py

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "-config"
  - "config-base.yaml"
  - ${args}

project: test-sweep

method: random

parameters:
  lr_init:
    distribution: log_uniform_values
    min: 6.e-5
    max: 5.e-3

  lr_exp_decay_per_epoch:
    distribution: uniform
    min: 0.75
    max: 0.98

  num_conv_layers:
    values: [1, 2, 3, 4, 5]
